### ISSUE TITLE
misspelled import gives cryptic error.

### ISSUE THREAD

**Issue by benmathes** [django-debug-toolbar/django-debug-toolbar#749]
In a django app `foo`, inside `foo/util.py`. If you add a misspelled import statement, e.g.
```python from rest_framework.serializers_misspelled import DateTimeField```. The correctly or removal of this misspelling fixes the problem.

It seems that DDT is squashing the import error and then failing later.

```
./manage.py runserver_plus
Traceback (most recent call last):
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/core/urlresolvers.py", line 565, in reverse
    extra, resolver = resolver.namespace_dict[ns]
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/core/urlresolvers.py", line 345, in namespace_dict
    self._populate()
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/core/urlresolvers.py", line 285, in _populate
    for pattern in reversed(self.url_patterns):
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/benmathes/programming/work/greylock/intel/intel/urls.py", line 6, in <module>
    admin.site.disable_action('delete_selected')
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 141, in disable_action
    del self._actions[name]
KeyError: 'delete_selected'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/debug_toolbar/settings.py", line 220, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/core/urlresolvers.py", line 575, in reverse
    key)
django.core.urlresolvers.NoReverseMatch: 'delete_selected' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benmathes/programming/work/greylock/intel/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/debug_toolbar/settings.py", line 232, in patch_all
    patch_root_urlconf()
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/debug_toolbar/settings.py", line 222, in patch_root_urlconf
    urlconf_module = import_module(settings.ROOT_URLCONF)
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/benmathes/programming/work/greylock/intel/intel/urls.py", line 6, in <module>
    admin.site.disable_action('delete_selected')
  File "/Users/benmathes/.virtualenvs/intel/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 141, in disable_action
    del self._actions[name]
KeyError: 'delete_selected'
```

**Comment by aaugustin** [comment]
To avoid this problem, use the "explicit setup" described in the documentation.

**Comment by benmathes** [comment]
Hi @aaugustin, thanks for the quick response. 

First, thanks for DDT, it makes so much of web dev super smooth. 

I agree that this is 100% not gamebreaking, and can be avoided. I only wanted to suggest a less-cryptic error, that's all.

**Comment by aaugustin** [comment]
Patch welcome... The automatic setup is convenient but it is prone to such problems because it does too much magic.

**Comment by aaugustin** [comment]
I'm closing this issue because I've done my best to solve this problem. I'll reopen it if someone submits a patch.
