### ISSUE TITLE
Cache panel doesn't support Django 1.9

### ISSUE THREAD

**Issue by gavinwahl** [django-debug-toolbar/django-debug-toolbar#751]
```
Traceback (most recent call last):
  File "django-debug-toolbar/debug_toolbar/toolbar.py", line 127, in get_panel_classes
    mod = import_module(panel_module)
  File ".virtualenvs/foo/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "django-debug-toolbar/debug_toolbar/panels/cache.py", line 9, in <module>
    from django.core.cache import (
ImportError: cannot import name 'get_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "django/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "django/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "django/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "django/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "django-debug-toolbar/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "django-debug-toolbar/debug_toolbar/settings.py", line 231, in patch_all
    patch_middleware_classes()
  File "django-debug-toolbar/debug_toolbar/settings.py", line 210, in patch_middleware_classes
    if not is_toolbar_middleware_installed():
  File "django-debug-toolbar/debug_toolbar/settings.py", line 190, in is_toolbar_middleware_installed
    from debug_toolbar.middleware import DebugToolbarMiddleware
  File "django-debug-toolbar/debug_toolbar/middleware.py", line 14, in <module>
    from debug_toolbar.toolbar import DebugToolbar
  File "django-debug-toolbar/debug_toolbar/toolbar.py", line 160, in <module>
    urlpatterns = DebugToolbar.get_urls()
  File "django-debug-toolbar/debug_toolbar/toolbar.py", line 154, in get_urls
    for panel_class in cls.get_panel_classes():
  File "django-debug-toolbar/debug_toolbar/toolbar.py", line 131, in get_panel_classes
    (panel_module, e))
django.core.exceptions.ImproperlyConfigured: Error importing debug panel debug_toolbar.panels.cache: "cannot import name 'get_cache'"
```

**Comment by aaugustin** [comment]
Fixed in #762.
