### ISSUE TITLE
django1.3 Error: cannot import name six

### ISSUE THREAD

**Issue by nvcken** [django-debug-toolbar/django-debug-toolbar#756]
My pip list
```
argparse (1.3.0)
Django (1.3)
django-authopenid (1.0.1)
django-clement (0.0.3)
django-debug-toolbar (1.3.2)
django-ga (0.2.0)
django-picklefield (0.3.2)
django-registration (1.0)
```
Which version django-debug-toolbar support django 1.3 ?

```
Unhandled exception in thread started by <bound method Command.inner_run of <django.contrib.staticfiles.management.commands.runserver.Command object at 0x101e38fd0>>
Traceback (most recent call last):
  File "/Users/nvcken/work/dirox/venv/lib/python2.6/site-packages/django/core/management/commands/runserver.py", line 88, in inner_run
    self.validate(display_num_errors=True)
  File "/Users/nvcken/work/dirox/venv/lib/python2.6/site-packages/django/core/management/base.py", line 249, in validate
    num_errors = get_validation_errors(s, app)
  File "/Users/nvcken/work/dirox/venv/lib/python2.6/site-packages/django/core/management/validation.py", line 36, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Users/nvcken/work/dirox/venv/lib/python2.6/site-packages/django/db/models/loading.py", line 146, in get_app_errors
    self._populate()
  File "/Users/nvcken/work/dirox/venv/lib/python2.6/site-packages/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name)
  File "/Users/nvcken/work/dirox/venv/lib/python2.6/site-packages/django/db/models/loading.py", line 78, in load_app
    models = import_module('.models', app_name)
  File "/Users/nvcken/work/dirox/venv/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/nvcken/work/dirox/venv/lib/python2.6/site-packages/debug_toolbar/models.py", line 5, in <module>
    from debug_toolbar import settings as dt_settings
  File "/Users/nvcken/work/dirox/venv/lib/python2.6/site-packages/debug_toolbar/settings.py", line 6, in <module>
    from django.utils import six
ImportError: cannot import name six
```

**Comment by aaugustin** [comment]
Django 1.3 has been out of security support for years. Sorry, you're on your own.

**Comment by nvcken** [comment]
Ok, I think We should upgrade at this time.
Thanks for help.

**Comment by Taniya2412** [comment]
Any body found an answer to this?
