### ISSUE TITLE
Creating a ModelForm without either the 'fields' attribute

### ISSUE THREAD

**Issue by priya124** [django-debug-toolbar/django-debug-toolbar#826]
Please help to solve this issue.the below mensioned error occured while i am insalling RatticDB on ubuntu 12.04

./manage.py syncdb --noinput
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/apps/RatticWeb/cred/models.py", line 18, in <module>
    class TagForm(ModelForm):
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 235, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form TagForm needs updating.

**Comment by priya124** [comment]
I am using Django 1.9.6 and Django-tagging 0.3.6 
I cannot update Django-tagging 0.3.6 from Django 0.4.3

**Comment by tim-schilling** [comment]
Is this related to the toolbar? You can use StackOverflow for general Django debugging help.

**Comment by priya124** [comment]
No it is not related to toolbar..
This error is occuring while ia am trying to install RatticDB open source password manager to ubuntu 12.04
it does'nt contain any toolbars.
please help me to solve that eroor

**Comment by tim-schilling** [comment]
@priya124 This is the Django Debug Toolbar, not django-tagging. You're looking for https://github.com/Fantomas42/django-tagging That said, you need to focus on upgrading your project to Django 1.9 first. It's going to be a bit difficult since you're jumping so many versions (5). You should start by reading through the release notes.

Closing the issue as it's unrelated to the toolbar.

**Comment by priya124** [comment]
Oh okay thank you for your kind reply

**Comment by priya124** [comment]
But i am already using Django 1.9.6 only..
Why should i update to 1.9 please tell me
