### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form TagForm needs updating.

### ISSUE THREAD

**Issue by priya124** [django-debug-toolbar/django-debug-toolbar#830]
Please help me to solve this error
./manage.py syncdb --noinput
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/apps/RatticWeb/cred/models.py", line 18, in <module>
    class TagForm(ModelForm):
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 235, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form TagForm needs updating.
administrator@ratticdb:/opt/apps/RatticWeb$ ./manage.py syncdb --noinput
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/apps/RatticWeb/cred/models.py", line 18, in <module>
    class TagForm(ModelForm):
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 235, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form TagForm needs updating.

**Comment by Nidhibarthwal** [comment]
Provie fields in your model's Meta Tag. Example:

class Meta:
        model = demo
        fields = '__all__'

**Comment by ashishpal07** [comment]
fields = '__all__'

**Comment by matthiask** [comment]
It's a bug in your code and has nothing to do with django-debug-toolbar. The Django forum or the users mailing list may be better places for questions such as this one (https://www.djangoproject.com/community/)

**Comment by abdidev1** [comment]
It's a bug in your code. Probably you have declared field, instead of "fields"
Provide "fields" in your model's Meta Tag. Example:

class Meta:
model = demo
 fields = [ ]

**Comment by Dattn0801** [comment]
> It's a bug in your code. Probably you have declared field, instead of "fields"
> Provide "fields" in your model's Meta Tag. Example:
> 
> class Meta:
> model = demo
> fields = [ ]

I don't know how I can fix it by migrate model

**Comment by matthiask** [comment]
Again, it has nothing to do with django-debug-toolbar and everything to do with the fact that your code has been written for an older version of Django. Here's the official documentation on model forms and I hope that you'll find the informations you require there: https://docs.djangoproject.com/en/3.2/topics/forms/modelforms/

The django users mailing list or the Django forum may be a better place to discuss issues such as this one in the future.
